// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcCursus.Models;

namespace MvcCursus.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200406141018_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcCursus.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            DateOfBirth = new DateTime(1994, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Peter",
                            Lastname = "Teeninga"
                        },
                        new
                        {
                            StudentID = 2,
                            DateOfBirth = new DateTime(1981, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Thang",
                            Lastname = "Le"
                        },
                        new
                        {
                            StudentID = 3,
                            DateOfBirth = new DateTime(1974, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Xander",
                            Lastname = "Wemmers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
